### ISSUE TITLE
Feedback on running `make()`

### ISSUE THREAD

**Issue by fmichonneau** [aammd/Predator_Phylogenetic_Diversity#30]
At this stage, I have only tried to build the manuscript and have `make()` run smoothly.

I'm having some trouble with Figshare. I hadn't used the R package before, but it seems that I can't authenticate correctly to be able to download the files within the session. That's probably just something wrong with my setup though. I downloaded the files manually, and modified the remake file to load them, and it seems to work.

- [x] In the `depends` you have listed for the manuscript, there is `doc/TABLE1.md` but the files doesn't exist in the repo. I think you need to add a target for it using `doc/TABLE1.Rmd`.

- [x] The markdown files rely on `formatting/myheader_*.tex` but these files are missing from the repo.

I'll look into the manuscript in more details in the next couple of days.

**Comment by aammd** [comment]
Thanks very much @fmichonneau ! I asked @sckott about your figshare experience -- it looks like using this might requre installation from a development branch of Rfigshare

**Comment by fmichonneau** [comment]
OK, thanks for letting me know. I'll give it another try. I'll try to provide feedback on the content of the paper soon!

**Comment by sckott** [comment]
i heard my name 👂
